# Generated by Django 4.2.1 on 2024-02-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prduct_name', models.CharField(max_length=70)),
                ('product_price', models.IntegerField(default=0)),
                ('product_detail', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='Product_images/')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
    ]
