# Generated by Django 4.2.1 on 2024-02-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prduct_name',
            new_name='product_name',
        ),
    ]
