# Generated by Django 4.2.1 on 2024-02-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_signup_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name_plural': 'Sign_Up'},
        ),
    ]
