# Generated by Django 4.2.1 on 2024-02-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_signup_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
