# Generated by Django 4.2.1 on 2024-02-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_large_size_sizes_remove_size_mediam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sizes',
            field=models.CharField(max_length=20),
        ),
    ]
